# Datenstrom Yellow extension settings

Extension: Breadcrumb
Version: 1.0.1
Description: Breadcrumb navigation.
Developer: Anna Svensson
Tag: feature
DownloadUrl: https://github.com/annaesvensson/yellow-breadcrumb/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-breadcrumb
DocumentationLanguage: en, de, sv
Published: 2026-09-25 19:06:45
Status: maintained
system/workers/breadcrumb.php: breadcrumb.php, create, update
